#-----------   TRAINER -------------
trainer:
  max_epochs: 100
  checkpoint: 
  pretrain: "/lustre/orion/nro108/scratch/xf9/checkpoints/climate/interm_rank_0_epoch_4.ckpt" 
  batch_size: 1
  buffer_size: 400
  num_workers: 2


# ---------------------------- MODEL -------------------------------------------
model:
  preset: res_slimvit
  lr: 2e-4
  weight_decay: 1e-5
  beta_1: 0.9
  beta_2: 0.99
  warmup_epochs: 2
  warmup_start_lr: 1e-7
  eta_min: 1e-8
  superres_mag: 4
  cnn_ratio: 4
  patch_size: 2
  embed_dim: 256
  depth: 6
  decoder_depth: 2
  num_heads: 4
  mlp_ratio: 4
  drop_path: 0.1
  drop_rate: 0.1

# ---------------------------- DATA -------------------------------------------
data:
  low_res_dir: {
    'INFER': "/lustre/orion/world-shared/lrn036/jyc/frontier/ClimaX-v2/data/ERA5-1hr-superres/0.25_deg/",
  }
  high_res_dir: {
    'INFER': "/lustre/orion/world-shared/lrn036/jyc/frontier/ClimaX-v2/data/ERA5-1hr-superres/0.25_deg/",
  }

  # input spatial resolution in km
  spatial_resolution: {
    'ERA5_1': 625,
    'ERA5_2': 111,
    'PRISM':  18,
    'INFER': 28,
  }



  default_vars: [
    "land_sea_mask",
    "orography",
    "lattitude",
    "prcp",
    "tmin",
    "tmax",
    "2m_temperature",
    "10m_u_component_of_wind",
    "10m_v_component_of_wind",
    "geopotential",
    "temperature",
    "specific_humidity",
    "total_precipitation",

  ]



  dict_in_variables: {
    'INFER': [
      "land_sea_mask",
      "orography",
      "lattitude",
      "2m_temperature",
      "10m_u_component_of_wind",
      "10m_v_component_of_wind",
      "geopotential",
      "temperature",
      "specific_humidity",
      "total_precipitation",
    ],
  }



  #output variable choices
  #   "t2m": "2m_temperature",
  #    "z500": "geopotential_500",
  #    "t850": "temperature_850",
  #    "u10": "10m_u_component_of_wind",
  #    "prcp": "prcp",
  #    "orography": "orography",


  dict_out_variables: {
    'INFER':[
      "2m_temperature",
#      "10m_u_component_of_wind",
#      "10m_v_component_of_wind",
    ],
  }
